# Generated by Django 3.2 on 2025-12-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('academic_year', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('currently_working_in', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
