# Generated by Django 3.2 on 2025-12-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrft', '0002_alumniregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumniregistration',
            old_name='currently_working_in',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='alumniregistration',
            name='password',
        ),
        migrations.AddField(
            model_name='alumniregistration',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alumniregistration',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
