# Generated by Django 3.2 on 2025-12-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smrft', '0003_auto_20251215_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniregistration',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='alumniregistration',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='alumniregistration',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
